version: '3.8'

services:
  backend:
    build: ./recursoshumanos-servicio
    ports:
      - "8085:8085"
    networks:
      - app-network
    environment:
      SPRING_APPLICATION_NAME: recursoshumanos
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rrhh
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      - db

  frontend:
    build: ./recursoshumanos-cliente
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: rrhh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
